openapi: 3.0.0
info:
  title: Laravel 実務講座 コレクション
  version: 1.0.0
  description: ''
servers:
  - url: '{{BASE_URL}}'
paths:
  /api/hello:
    get:
      summary: hello
      responses: {}
      tags:
        - Lesson01
  /api/fruits:
    get:
      summary: fruits
      responses: {}
      tags:
        - Lesson01
    post:
      summary: fruits
      responses: {}
      tags:
        - Lesson01
  /api/fruits/{fruitId}:
    get:
      summary: fruits_id
      responses: {}
      tags:
        - Lesson01
    parameters:
      - name: fruitId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: '1'
  /api/users:
    get:
      summary: users
      responses: {}
      tags:
        - Lesson02
  /api/users/{userId}:
    patch:
      summary: users_id
      parameters:
        - name: X-XSRF-TOKEN
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{XSRF-TOKEN}}'
        - name: Referer
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Referer}}'
        - name: Origin
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Origin}}'
      responses: {}
      tags:
        - Lesson02
    parameters:
      - name: userId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: '1'
  /api/me:
    get:
      summary: 認証済みユーザー取得
      parameters:
        - name: Referer
          in: header
          schema:
            type: string
          example: '{{Referer}}'
        - name: Origin
          in: header
          schema:
            type: string
          example: '{{Origin}}'
      responses: {}
      tags:
        - Lesson06
      requestBody:
        content:
          application/json:
            schema:
              type: object
  /login:
    post:
      summary: ログイン
      parameters:
        - name: X-XSRF-TOKEN
          in: header
          schema:
            type: string
          example: '{{XSRF-TOKEN}}'
        - name: Referer
          in: header
          schema:
            type: string
          example: '{{Referer}}'
        - name: Origin
          in: header
          schema:
            type: string
          example: '{{Origin}}'
      responses: {}
      tags:
        - Lesson06
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
            example:
              email: test@example.com
              password: password
  /logout:
    post:
      summary: ログアウト
      parameters:
        - name: X-XSRF-TOKEN
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{XSRF-TOKEN}}'
        - name: Referer
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Referer}}'
        - name: Origin
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Origin}}'
      responses: {}
      tags:
        - Lesson06
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
            example:
              email: test@example.com
              password: password
  /api/courses:
    get:
      summary: 講座一覧
      parameters:
        - name: Referer
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Referer}}'
        - name: Origin
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Origin}}'
      responses: {}
      tags:
        - Lesson09
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
            example:
              name: 更新テスト
    post:
      summary: 講座登録
      parameters:
        - name: X-XSRF-TOKEN
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{XSRF-TOKEN}}'
        - name: Referer
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Referer}}'
        - name: Origin
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Origin}}'
      responses: {}
      tags:
        - Lesson09
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                capacity:
                  type: integer
                status:
                  type: string
            example:
              title: 講座名テスト
              description: 説明説明
              capacity: 1
              status: draft
  /api/courses/{courseId}:
    get:
      summary: 講座詳細
      parameters:
        - name: Referer
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Referer}}'
        - name: Origin
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Origin}}'
      responses: {}
      tags:
        - Lesson09
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
            example:
              name: 更新テスト
    parameters:
      - name: courseId
        in: path
        required: true
        schema:
          type: integer
        example: '1'
    patch:
      summary: 講座更新
      parameters:
        - name: X-XSRF-TOKEN
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{XSRF-TOKEN}}'
        - name: Referer
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Referer}}'
        - name: Origin
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Origin}}'
      responses: {}
      tags:
        - Lesson09
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                capacity:
                  type: integer
                status:
                  type: string
            example:
              title: 講座名更新テスト
              capacity: 10
              status: active
    delete:
      summary: 講座削除
      parameters:
        - name: X-XSRF-TOKEN
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{XSRF-TOKEN}}'
        - name: Referer
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Referer}}'
        - name: Origin
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Origin}}'
      responses: {}
      tags:
        - Lesson09
      requestBody:
        content:
          application/json:
            schema:
              type: object
  /api/courses/{courseId}/attendances:
    post:
      summary: 受講登録
      parameters:
        - name: X-XSRF-TOKEN
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{XSRF-TOKEN}}'
        - name: Referer
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Referer}}'
        - name: Origin
          in: header
          required: false
          deprecated: false
          schema: {}
          example: '{{Origin}}'
      responses: {}
      tags:
        - Lesson11
      requestBody:
        content:
          application/json:
            schema:
              type: object
    parameters:
      - name: courseId
        in: path
        required: true
        deprecated: false
        schema: {}
        example: '27'
